# Copyright (c) 2023 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: micro-ROS
      url-base: https://github.com/micro-ROS
    - name: catie-6tron
      url-base: https://github.com/catie-aq
  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.5.0
      import:
        name-allowlist:
          - cmsis
          - hal_stm32
          - fatfs
          - nanopb
    - name: micro_ros_zephyr_module
      remote: micro-ROS
      revision: humble
      path: modules/micro_ros_zephyr_module
    - name: zephyr_hls-lfcd2
      remote: catie-6tron
      revision: master
      path: 6tron/hls-lfcd2
    - name: 6tron-manifest
      remote: catie-6tron
      repo-path: zephyr_6tron-manifest
      revision: v3.5.0+202402
      path: 6tron/6tron-manifest
      import:
        name-allowlist:
          - 6tron-connector
          - zest-core-stm32l4a6rg
