# Copyright (c) 2023 CATIE
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos
    - name: micro-ROS
      url-base: https://github.com/micro-ROS
    - name: catie-6tron
      url-base: https://github.com/catie-aq

  group-filter: [+optional]

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: main
      import: true
    - name: micro_ros_zephyr_module
      remote: catie-6tron
      revision: fix/zephyr-3.2-header-jazzy
      path: modules/micro_ros_zephyr_module
    - name: zephyr_hls-lfcd2
      remote: catie-6tron
      revision: master
      path: 6tron/hls-lfcd2
    - name: 6tron-manifest
      remote: catie-6tron
      repo-path: zephyr_6tron-manifest
      revision: v3.7.0+202408
      path: 6tron/6tron-manifest
      import:
        name-allowlist:
          - 6tron_connector
          - zest_core_stm32h753zi
          - zest_interface_ethernet
    - name: ldrobot-ld19
      remote: catie-6tron
      repo-path: zephyr_ldrobot-ld19
      revision: main
      path: 6tron/ldrobot-ld19
    - name: zest_radio_wifi
      remote: catie-6tron
      repo-path: zephyr_zest-radio-wifi
      revision: 6-make-change-to-be-compatible-with-zephyr-370
      path: 6tron/shields/zest_radio_wifi
