name: "Build"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

jobs:
  zephyr-application:
    strategy:
      matrix:
        application: [ "app/base_application", "app/lidar_example" ]
    uses: catie-aq/zephyr_workflows/.github/workflows/application.yml@main
    with:
      container: "ghcr.io/catie-aq/zephyr_docker:v0.26.14"
      application: ${{ matrix.application }}
      board: "zest_core_stm32h753zi"
      blobs: "hal_nordic"
      extra_cmd: "pip3 install catkin_pkg lark-parser empy colcon-common-extensions"

    secrets:
      personal_access_token: ${{ secrets.PAT }}
