name: "Release"

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  zephyr-application:
    uses: catie-aq/zephyr_workflows/.github/workflows/application.yml@main
    with:
      container: "zephyrprojectrtos/ci:v0.26.14"
      application: app/lidar_example
      board: "zest_core_stm32h753zi"
      blobs: "hal_nordic"
      extra_cmd: "pip3 install catkin_pkg lark-parser empy colcon-common-extensions"
      pem_key_path: app/base_application/key.pem
      artifact: "build/zephyr/zephyr.signed.bin"

    secrets:
      personal_access_token: ${{ secrets.PAT }}
      pem_key: ${{ secrets.KEY }}

  release:
    runs-on: sonu-github-arc
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: "app/base_application"
        path: "tmp"

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.PAT }}
        draft: true
        tag_name: ${{ github.ref }}
        generate_release_notes: true
        files: tmp/*.bin
