name: "Zephyr Applications CI/CD"

on:
  push:
    paths-ignore:
      - 'README.md'
  workflow_dispatch:

jobs:
  zephyr-application:
    strategy:
      matrix:
        application: [ "app/base_application", "app/lidar_example" ]
    uses: catie-aq/zephyr_workflows/.github/workflows/application.yml@main
    with:
      application: ${{ matrix.application }}
      board: "zest_core_stm32l4a6rg"
      extra_cmd: "pip3 install catkin_pkg lark-parser empy colcon-common-extensions"
      container: "zephyrprojectrtos/ci:v0.24.13"

    secrets:
      personal_access_token: ${{ secrets.PAT }}
